#!/bin/sh /etc/rc.common

USE_PROCD=1
START=96
STOP=10

start_service() {
	mkdir -p /run/mihomo || return 1
	chown root:root /run/mihomo || return 1
	chmod 0700 /run/mihomo || return 1

	procd_open_instance
	procd_set_param command /usr/sbin/luci-mihomo
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param limits nofile="4096 4096"
	procd_close_instance
}

reload_service() {
	stop
	start
}
